name: AUR Publish PKGBUILD-git

on:
  push:
    branches: [ "main" ]
    paths:
      - "PKGBUILD-git"

jobs:
  publish:
    name: AUR Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - uses: KSXGitHub/github-actions-deploy-aur@v4.1.1
        with:
          pkgname: noctyra-dotfiles-git
          pkgbuild: ./PKGBUILD-git
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: Update Noctyra dotfiles package
          ssh_keyscan_types: rsa,ecdsa,ed25519